[AllPix]
log_level = "FATAL"
log_format = "DEFAULT"
number_of_events = 50000
detectors_file = ""
model_paths = "./"
multithreading = true
workers=16

[GeometryBuilderGeant4]
world_material = "air"
world_margin_percentage = 0
world_minimum_margin = 50mm 50mm 50mm

[DepositionGeant4]
physics_list = FTFP_BERT_LIV
# Replicate CERN SPS beam parameters
enable_pai = true           # Photoabsorption Ionization model
source_type = "beam"
particle_type = "pi+"
source_energy = 120GeV
source_position = 0mm 0mm -10mm
beam_size = 40um
beam_direction = 0 0 1
record_all_tracks = false
number_of_particles = 1
max_step_length = 0.1um     # default is 1um
deposit_in_frontside_implants = true
deposit_in_backside_implants = false
output_plots = true
output_plots_scale = 20ke

[DopingProfileReader]
model = "mesh"
file_name = "blancket_for_aptsoa16jan_65nm_3D_4_8V_0_4V_thick25_pitch10_try2node107_DopingConcentration.apf"
field_mapping = PIXEL_FULL
field_scale = 1 1

[ElectricFieldReader]
model = "mesh"
file_name = "blancket_for_aptsoa16jan_65nm_3D_4_8V_0_4V_thick25_pitch10_try2node107_ElectricField.apf"
field_mapping = PIXEL_FULL
field_scale = 1 1 

[WeightingPotentialReader]
model = "mesh"
file_name = "wp_blancket_for_aptsoa16jan_65nm_3D_4_8V_0_4V_thick25_pitch10_try2node107_ElectrostaticPotential.apf"
field_mapping = PIXEL_FULL
field_scale = 1 1
output_plots = true

#To be used only when electric field is retrieved from TCAD simulation
[TransientPropagation]
temperature = 300K
mobility_model = "masetti_canali"
dopant_n = "phosphorus"
recombination_model = "srh_auger"
trapping_model = none
detrapping_model = none
fluence = 0
charge_per_step = 10  # use default value
timestep = 0.005ns    # default is 0.01 ns
integration_time = 25ns 

[PulseTransfer]
collect_from_implant = true
timestep = 0.025ns                 # Only used if no pulse information is available for the propagated charge object - default value is 0.01ns .

[CSADigitizer]
model = "simple"
integration_time = 100ns
baseline_padding_time = 50ns
# integration_time = 1us           # settings of TB oscilloscope
# baseline_padding_time = 250ns    # settings of TB oscilloscope
sigma_noise = 1.5mV #was 0.8mV
ignore_polarity = false
threshold = -5mV                    # corresponding to about 100 electrons threshold if 3 fF feedback capacitance is used
feedback_capacitance = 2.95e-15C/V    #in Farad: passed factor C/g computed from Fe55 calibration
rise_time_constant = 0.18ns        # 2.2 factor between time constant and rise time
feedback_time_constant = 2.5us     # pulse fall time constant

[DetectorHistogrammer]
granularity = 10 10
max_cluster_charge = 5ke
name = "APTS_OPAMP"
matching_cut = 15um 15um 

