[AllPix]
log_level = "FATAL"
log_format = "DEFAULT"
number_of_events = 10000
detectors_file = ""
model_paths = "./"
multithreading = true
workers=16

[GeometryBuilderGeant4]
world_material = "air"
world_margin_percentage = 0
world_minimum_margin = 50mm 50mm 50mm

[DepositionGeant4]
physics_list = FTFP_BERT_LIV
# Replicate CERN SPS beam parameters
enable_pai = true           # Photoabsorption Ionization model
source_type = "beam"
particle_type = "pi+"
source_energy = 120GeV
source_position = 0mm 0mm -10mm
beam_size = 40um
beam_direction = 0 0 1
record_all_tracks = false
number_of_particles = 1
max_step_length = 0.1um     # default is 1um
# range_cut = 2um           # default is 1/5 of the shortest pixel feature - it affects the cluster shape
deposit_in_frontside_implants = true
deposit_in_backside_implants = false
output_plots = true
output_plots_scale = 20ke

[DopingProfileReader]
model = "mesh"
file_name = "blancket_for_aptsoa16jan_65nm_3D_4_8V_0_4V_thick25_pitch10_try2node107_DopingConcentration.apf"
field_mapping = PIXEL_FULL
field_scale = 1 1
# output_plots = true

[ElectricFieldReader]
model = "mesh"
file_name = "blancket_for_aptsoa16jan_65nm_3D_4_8V_0_4V_thick25_pitch10_try2node107_ElectricField.apf"
field_mapping = PIXEL_FULL
field_scale = 1 1 # 0.95759234, 1.04166667
# output_plots = true

[WeightingPotentialReader]
model = "mesh"
file_name = "wp_blancket_for_aptsoa16jan_65nm_3D_4_8V_0_4V_thick25_pitch10_try2node107_ElectrostaticPotential.apf"
field_mapping = PIXEL_FULL
field_scale = 1 1
output_plots = true

#To be used only when electric field is retrieved from TCAD simulation
[TransientPropagation]
temperature = 300K
mobility_model = "masetti_canali"
dopant_n = "phosphorus"
recombination_model = "srh_auger"
trapping_model = none
detrapping_model = none
fluence = 0
charge_per_step = 10  # use default value
timestep = 0.005ns    # default is 0.01 ns
integration_time = 25ns 

# output_plots = true
# output_plots_use_pixel_units = true
# output_plots_align_pixels = true
# output_linegraphs = true # check the progation of charge in substrate 
# output_linegraphs_collected = true # plotting only charges that was collected
# output_linegraphs_recombined = true
# output_linegraphs_trapped = true
# output_plots_step = 0.01ns
# output_animations = true

[PulseTransfer]
# max_depth_distance = 1um         # needed only if the detector has no implant defined
collect_from_implant = true
timestep = 0.025ns                 # Only used if no pulse information is available for the propagated charge object - default value is 0.01ns .
# output_pulsegraphs = true
# output_plots = true
# output_plots_scale = 5ke
# output_plots_bins = 250


[CSADigitizer]
model = "simple"
integration_time = 100ns
baseline_padding_time = 50ns
sigma_noise = 1.5mV #was 0.8mV
ignore_polarity = false
threshold = -5mV                    # corresponding to about 100 electrons threshold if 3 fF feedback capacitance is used
feedback_capacitance = 3e-15C/V    # passed factor C/g computed from Fe55 calibration
rise_time_constant = 0.18ns        # 2.2 factor between time constant and rise time
feedback_time_constant = 2.5us     # pulse fall time constant
# output_plots = true
# output_plots_scale = 5ke
# output_plots_bins = 250
# output_pulsegraphs = true

[DetectorHistogrammer]
granularity = 10 10
max_cluster_charge = 5ke
name = "APTS_OPAMP"
matching_cut = 15um 15um 

# [VisualizationGeant4]
# mode = "terminal"
# # mode = "gui"
# view_style = "surface"
# accumulate = true
# accumulate_time_step = 2s
# draw_hits = true
# display_trajectories = true
# simple_view = false

[ROOTObjectWriter]
file_name = "AllPix_objects_test.root"
include = "MCTrack", "MCParticle", "PixelCharge", "PixelPulse", "PixelHit", "DepositedCharge"
