model = init
region = "Substrate"
observable = "ElectrostaticPotential"
xyz = x z y
divisions = 500 500 1250
observable_units = ""
interpolate = false
allow_failure = true

# to convert .dat .grd fields use:
# source /cvmfs/clicdp.cern.ch/software/allpix-squared/latest/x86_64-el9-clang16-opt/setup.sh 
# mesh_converter -c wp_calc_convert.conf -f tcad_field_0.4V
# mesh_converter -c wp_calc_convert.conf -f tcad_field_0.3V
# for visualization of the fields use:
# mesh_plotter -f  wp_tcad_field_0.4V_ElectrostaticPotential.apf -s
