model = apf
region = "Substrate"
observable = "DopingConcentration"
xyz = x z y
divisions = 500 500 1250
observable_units = um
vector_field = false
interpolate = false
allow_failure = true
workers = 16 #defaults to max

