[AllPix]
log_level = "FATAL"
log_format = "DEFAULT"
number_of_events = 10000 
detectors_file = ""
model_paths = "./"
multithreading = true
workers=10

[GeometryBuilderGeant4]
world_material = "air"
world_margin_percentage = 0
world_minimum_margin = 50mm 50mm 50mm

[DepositionGeant4]
physics_list = FTFP_BERT_LIV
source_type= "macro"
file_name = ./Fe55photons.mac
max_step_length = 1.0um
number_of_particles = 1
output_plots = true 

[DopingProfileReader]
model = "mesh"
file_name = ""
field_mapping = PIXEL_FULL
field_scale = 1 1
# output_plots = true

[ElectricFieldReader]
model = "mesh"
file_name = ""
field_mapping = PIXEL_FULL
field_scale = 1 1 # 0.95759234, 1.04166667
# output_plots = true

[WeightingPotentialReader]
model = "mesh"
file_name = ""
field_mapping = PIXEL_FULL
field_scale = 1 1
output_plots = true

#To be used only when electric field is retrieved from TCAD simulation
[TransientPropagation]
temperature = 300K
mobility_model = "masetti_canali"
dopant_n = "phosphorus"
recombination_model = "srh_auger"
trapping_model = none
detrapping_model = none
fluence = 0
charge_per_step = 10  # use default value 10
timestep = 1ps       # default is 0.01 ns
integration_time = 25ns  ##stefania using 20ns 

[PulseTransfer]
collect_from_implant = true
timestep = 0.025ns                 # Only used if no pulse information is available for the propagated charge object - default value is 0.01ns .

[CSADigitizer]
model = "simple"
integration_time = 100ns
baseline_padding_time = 50ns
sigma_noise = 1.5mV #was 0.8mV
ignore_polarity = false
threshold = -5mV                    # corresponding to about 100 electrons threshold if 3 fF feedback capacitance is used
feedback_capacitance = 3e-15C/V    # passed factor C/g computed from Fe55 calibration
rise_time_constant = 0.18ns        # 2.2 factor between time constant and rise time
feedback_time_constant = 2.5us     # pulse fall time constant

[DetectorHistogrammer]
granularity = 10 10
max_cluster_charge = 5ke
name = "APTS_OPAMP"
matching_cut = 15um 15um 

[ROOTObjectWriter]
file_name = "AllPix_objects_test.root"
include =  "PixelPulse",  "DepositedCharge", "PixelCharge" 