[AllPix]
log_level = "FATAL"
log_format = "DEFAULT"
number_of_events = 10 
detectors_file = ""
model_paths = "./"
output_directory = ""
multithreading = true
workers=8
root_file="plots_0.root"

[GeometryBuilderGeant4]
world_material = "air"
world_margin_percentage = 0
world_minimum_margin = 50mm 50mm 50mm

[DepositionGeant4]
physics_list = FTFP_BERT_LIV
source_type= "macro"
file_name = ./Fe55photons.mac
max_step_length = 1.0um
number_of_particles = 1
output_plots = true 


[DopingProfileReader]
model = "mesh"
file_name = ""
field_mapping = PIXEL_FULL
field_scale = 1 1
# output_plots = true

[ElectricFieldReader]
model = "mesh"
file_name = ""
field_mapping = PIXEL_FULL
field_scale = 1 1 
# output_plots = true

[WeightingPotentialReader]
model = "mesh"
file_name = ""
field_mapping = PIXEL_FULL
field_scale = 1 1
output_plots = true


#To be used only when electric field is retrieved from TCAD simulation
[TransientPropagation]
temperature = 300K
mobility_model = "masetti_canali"
dopant_n = "phosphorus"
recombination_model = "srh_auger"
trapping_model = none
detrapping_model = none
fluence = 0
charge_per_step = 10  # use default value 10
timestep = 1ps    # default is 0.01 ns
integration_time = 1.5ns  

output_plots = true
output_plots_use_pixel_units = true
output_plots_align_pixels = true
output_linegraphs = true 

output_plots_step = 0.01ns
output_animations = true
